name:  "GivTCP Patched"
description:  "TCP Modbus connection to MQTT/REST for Givenergy Battery/PV Invertors"
version:  "3.5"
image: demgnz/giv_tcp:patched
slug:  "givtcp-patched"
homeassistant_api: true
hassio_api: true
init:  true
ingress: true
services:
  - "mqtt:want"
map:
  - config:rw
  - ssl
boot:  auto
url:  https://github.com/mg-nz/giv_tcp
legacy:  true
arch: 
  - aarch64
  - amd64
host_network: true
